require "config.options"
require "config.kickstart"
-- require "config.colorsheme"
-- require "config.whichkey"
-- require "config.cmp"
-- require "config.comment"
-- require "config.autopairs"
-- require "config.lualine"
-- require "config.lsp"
-- require "config.dashboard"
-- require "config.telescope"
-- require "config.keymap"
-- require "config.git"
-- require "config.treesitter"
